-- sql/duckdb/beaderstadt_library_query_kpi_checkouts.sql
-- ============================================================
-- PURPOSE
-- ============================================================
-- Calculate a Key Performance Indicator (KPI) for the library domain using DuckDB SQL.
--
-- KPI DRIVES THE WORK:
-- In analytics, we do not start with "write a query."
-- We start with a KPI that supports an actionable decision.
--
-- ACTIONABLE OUTCOME (EXAMPLE):
-- We want to identify which branches generate the most activity and fines so we can:
-- - allocate staffing during high-traffic periods
-- - understand usage patterns across branches
-- - identify underperforming branches
-- - improve library resource planning
--
-- In this example, our KPI is Total fines collected by branch + checkout activity
--
-- ANALYST RESPONSIBILITY:
-- Analysts are responsible for determining HOW to get the information
-- that informs the KPI and supports action.
-- That means:
-- - identifying the needed tables,
-- - joining them correctly,
-- - selecting the right measures,
-- - aggregating at the correct level (branch),
-- - and presenting results in a way that supports decision-making.
--
-- ASSUMPTION:
-- We always run all commands from the project root directory.
--
-- EXPECTED PROJECT PATHS (relative to repo root):
--   SQL:  sql/duckdb/beaderstadt_library_query_kpi_checkouts.sql
--   DB:   artifacts/duckdb/library.duckdb
--
--
-- ============================================================
-- TOPIC DOMAINS + 1:M RELATIONSHIPS
-- ============================================================
-- OUR DOMAIN: LIBRARY
-- Two tables in a 1-to-many relationship (1:M):
-- - branch (1): independent/parent table
-- - checkout (M): dependent/child table
--
-- HOW THIS RELATES TO OUR KPI:
-- - The branch table tells us "which branch" (branch_id, branch_name, city, system_name).
-- - The checkout table contains the measurable activity (fine_amount, checkout_date).
-- - To compute total fines collected by branch, we must:
--   1) connect each checkout to its branch (JOIN on branch_id),
--   2) aggregate fine amounts at the branch level (GROUP BY branch).
--   3) Summarize activity per branch
--
-- ============================================================
-- KPI DEFINITION
-- ============================================================
-- KPI NAME: Total Fines and Checkout Activity by Branch
--
-- KPI QUESTION:
-- "How much checkout activity and fine collection is generated by each branch?"
--
-- MEASURE:
-- - total_fine_amount = SUM(checkout.fine_amount)
-- - checkout_count = COUNT(checkout.checkout_id)
-- - avg_fine_amount = AVG(checkout.fine_amount)
--
-- GRAIN (LEVEL OF DETAIL):
-- - one row per branch
--
-- OUTPUT (WHAT DECISION-MAKERS NEED):
-- - branch identifier and name
-- - branch location (city, system)
-- - total number of checkouts
-- - total fines collected
-- - average fine per checkout
--
--
-- ============================================================
-- EXECUTION: GET THE INFORMATION THAT INFORMS THE KPI
-- ============================================================
-- Strategy:
-- - JOIN branch (1) to checkout (M)
-- - GROUP BY branch
-- - SUM fine amounts to measure total fines
-- - COUNT checkouts to measure usage volume
-- - ORDER results to highlight highest activity branches
--
SELECT
  b.branch_id,
  b.branch_name,
  b.city,
  b.system_name,
  COUNT(c.checkout_id) AS checkout_count,
  ROUND(SUM(c.fine_amount), 2) AS total_fine_amount,
  ROUND(AVG(c.fine_amount), 2) AS avg_fine_amount
FROM branch AS b
JOIN checkout AS c
  ON c.branch_id = b.branch_id
GROUP BY
  b.branch_id,
  b.branch_name,
  b.city,
  b.system_name
ORDER BY total_fine_amount DESC, checkout_count DESC;

